/* gait2dMEX.c
 * C source code for the MEX function gait2dMEX.
 *
 * Ton van den Bogert, February 2026
 *
 * MEX function usage: [Q,dQdq,dQdqd,dQdqdd,FK,GRF] = gait2dMEX(q,qd,qdd,v)
 *
 * See makeGait2dMEX.m for more information
 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "mex.h"

#define NDOFS 9         // number of degrees of freedom
#define NSEGMENTS 7     // number of body segments

// =========================================================================
// mexFunction: this is the actual MEX function interface
// =========================================================================
void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    
	// MEX function pointers to inputs and output matrices
	double *q, *qd, *qdd, *vptr;
    double *Q, *Q_q, *Q_qd, *Q_qdd, *FK, *GRF;
	
    // Check number of inputs and outputs
    if ( (nrhs != 1) && (nrhs != 4) ) {
        mexErrMsgTxt("gait2dMEX: must have 1 input (q) or 4 inputs (q,qd,qdd,v)");		
    }
    
    // Get pointers to the inputs
    q   = mxGetPr(prhs[0]);
    if (nrhs > 1) {
        qd  = mxGetPr(prhs[1]);
        qdd = mxGetPr(prhs[2]); 
        vptr = mxGetPr(prhs[3]); 
    }
    
    // Create the output matrices: Q,Q_q,Q_qd,Q_qdd,GRF
    // and set the pointers for matlab to receive their contents
    plhs[0] = mxCreateNumericMatrix(NDOFS, 1, mxDOUBLE_CLASS, mxREAL);   
    Q = mxGetPr(plhs[0]);
    
    // TODO: we can save some time not allocating these unless nlhs
    // indicates that these outputs were requested.  But then we also 
    // need to have "if (nlhs < ...) return;" in several places in tmp1.c,
    // to prevent memory fault due to pointers not initialized
    plhs[1] = mxCreateNumericMatrix(NDOFS, NDOFS, mxDOUBLE_CLASS, mxREAL);   
    Q_q = mxGetPr(plhs[1]);

    plhs[2] = mxCreateNumericMatrix(NDOFS, NDOFS, mxDOUBLE_CLASS, mxREAL);   
    Q_qd = mxGetPr(plhs[2]);

    plhs[3] = mxCreateNumericMatrix(NDOFS, NDOFS, mxDOUBLE_CLASS, mxREAL);   
    Q_qdd = mxGetPr(plhs[3]);

    plhs[4] = mxCreateNumericMatrix(3*NSEGMENTS, 1, mxDOUBLE_CLASS, mxREAL);   
    FK = mxGetPr(plhs[4]);

    plhs[5] = mxCreateNumericMatrix(6, 1, mxDOUBLE_CLASS, mxREAL);   
    GRF = mxGetPr(plhs[5]);

    // insert the code generated by the makeGait2dMEX matlab function.  
    // that code will fill the output matrices we have just allocated
    #include "tmp1.c"   

}
